
name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==3.4.3
  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==0.5.1
    - autodoc==0.5.0
    - sphinxcontrib-packages==1.0.1
    - sphinxcontrib-napoleon==0.7
    - sphinx-autopackagesummary==1.3
    - sphinx-hoverxref==0.5b1
    - git://github.com/SuperKogito/sphinxcontrib-pdfembed@main
    - sphinxcontrib-slide==0.3.0
    - numpydoc==1.1.0
    - scipy==1.6.3
    - matplotlib==3.4.1
    - sphinx-panels==0.5.2
    - sphinx-togglebutton==0.2.3
